### PR TITLE
Check for recursion

### PR DESCRIPTION
**Pull request by hbiede**
Kinda dirty way of doing it, but it works

### CODE REVIEW

**Comment by cbourke** [comment]
Actually, I think this might be better achievable using a StackWalker.  You can create a stack walker and execute their recursive function, then check to see there were at least 2 calls (or better yet an expected number of calls to ensure they did the full recursion).  I'll take a look later but if you want to dive in go ahead.

**Comment by hbiede** [comment]
Not certain how that would work here. I don't have experience with that particular API, but it only seems able to collected stack entries from the current thread, which wouldn't work from the top level function because the recursive function doesn't exist on the stack before or after, and a separate thread wouldn't be able to see it. I may be mis-reading this however

**Comment by cbourke** [comment]
Yeah, after looking into it for far too long, I don't think it is possible at least with that API.  You'd have to have some observer process deeper in the JVM to "watch" a thread's stack and this is far too much just to check a lab.

**Comment by cbourke** [comment]
Good enough solution though.

**Pull request merged**
